### Login
POST localhost:8080/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@abc.com",
  "password": "admin"
}


### Register
POST localhost:8080/auth/signup
Accept: application/json
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@abc.com",
  "password": "admin"
}

### Get All Users
GET localhost:8080/users/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjFAYWJjLmNvbSIsImlhdCI6MTcyMzEzNjYxNSwiZXhwIjoxNzIzMTM3MjE1fQ.TcCDGE7swEFYrYj_PaLhcDIMscIZkrfnd5x_v8092QM

### Get Current User
GET localhost:8080/users/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhYmMuY29tIiwiaWF0IjoxNzIzMTgxMDQ1LCJleHAiOjE3MjMxODE2NDV9.zlNbVhYHgs7a39mBG8wf0YF-qHcrDOUV8zzvvccVDDI